# Generated by Django 5.1.2 on 2024-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_weather_recorded_at_weather_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature_threshold', models.FloatField(default=35.0)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
