# Generated by Django 5.1.2 on 2024-10-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='feels_like',
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='avg_humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='avg_wind_speed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
