# Generated by Django 5.1.2 on 2024-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_remove_alertpreference_humidity_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertpreference',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='alertpreference',
            name='weather_condition',
            field=models.CharField(max_length=100),
        ),
    ]
