# Generated by Django 5.1.2 on 2024-10-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_alter_dailysummary_avg_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpreference',
            name='humidity_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
